echo-client-c: client.c
	cc ./client.c -o echo-client-c
	./echo-client-c

echo-server-c: server.c
	cc ./server.c -o echo-server-c
	./echo-server-c

daylight-client-c: daylightClient.c daylightClient.h
	cc ./daylightClient.c ./daylightClient.h -o daylight-client
	./daylight-client
